= References

== Why do we have an extra loadbalancer node ?

When we create a cluster with k3d and check the number of nodes with both commands `kubectl get nodes` and `k3d node list`, we can see in the later, that we have an additional loadbalancer node that we didn't ask explicitely.

[source,bash]
----      
$ k3d cluster create demolb                     

$ kubectl get nodes
NAME                  STATUS   ROLES    AGE   VERSION
k3d-demolb-server-0   Ready    master   13s   v1.18.9+k3s1

$ k3d node list   
NAME                  ROLE           CLUSTER   STATUS
k3d-demolb-server-0   server         demolb    running
k3d-demolb-serverlb   loadbalancer   demolb    running
----

This loadbalancer node is an additional componant allowing to redirect the trafic from your host's network, to the docker network.
It is actually a simple nginx server, running in a docker container outside of the kubernetes using port mapping to expose the Kubernetes API port on your host's network.

[source,bash]
.the kubectl cluster-info shows the url to access the kubernetes API
----    
$ kubectl cluster-info     
Kubernetes master is running at https://0.0.0.0:40485
CoreDNS is running at https://0.0.0.0:40485/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
Metrics-server is running at https://0.0.0.0:40485/api/v1/namespaces/kube-system/services/https:metrics-server:/proxy
----

[source,bash]
.nginx running as docker container exposing Kubernetes API
----    
$ docker ps -a 
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS              PORTS                             NAMES
c1b252446854        rancher/k3d-proxy:v3.1.1   "/bin/sh -c nginx-pr…"   19 minutes ago      Up 19 minutes       80/tcp, 0.0.0.0:40485->6443/tcp   k3d-demolb-serverlb
242515343af3        rancher/k3s:v1.18.9-k3s1   "/bin/k3s server --t…"   19 minutes ago      Up 19 minutes                                         k3d-demolb-server-0
----

[source,bash]
.Containers having an IP address on the docker network
----
$ docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' k3d-demolb-serverlb
172.26.0.3

$ docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' k3d-demolb-server-0
172.26.0.2
----


== How can I reach a service in Kubernetes from my host ?

By default, k3s 


k get po,svc,daemonset --all-namespaces -o wide|grep 
[source,bash]
----
k get po,svc,daemonset --all-namespaces -o wide
NAMESPACE     NAME                                         READY   STATUS      RESTARTS   AGE   IP          NODE                  NOMINATED NODE   READINESS GATES
kube-system   pod/local-path-provisioner-6d59f47c7-skfgf   1/1     Running     0          24m   10.42.0.2   k3d-demolb-server-0   <none>           <none>
kube-system   pod/metrics-server-7566d596c8-d45mn          1/1     Running     0          24m   10.42.0.5   k3d-demolb-server-0   <none>           <none>
kube-system   pod/helm-install-traefik-smhq9               0/1     Completed   0          24m   10.42.0.4   k3d-demolb-server-0   <none>           <none>
kube-system   pod/svclb-traefik-p9rmc                      2/2     Running     0          23m   10.42.0.6   k3d-demolb-server-0   <none>           <none>
kube-system   pod/coredns-7944c66d8d-zdz46                 1/1     Running     0          24m   10.42.0.3   k3d-demolb-server-0   <none>           <none>
kube-system   pod/traefik-758cd5fc85-ktns6                 1/1     Running     0          23m   10.42.0.7   k3d-demolb-server-0   <none>           <none>

NAMESPACE     NAME                         TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE   SELECTOR
default       service/kubernetes           ClusterIP      10.43.0.1       <none>        443/TCP                      24m   <none>
kube-system   service/kube-dns             ClusterIP      10.43.0.10      <none>        53/UDP,53/TCP,9153/TCP       24m   k8s-app=kube-dns
kube-system   service/metrics-server       ClusterIP      10.43.152.202   <none>        443/TCP                      24m   k8s-app=metrics-server
kube-system   service/traefik-prometheus   ClusterIP      10.43.65.243    <none>        9100/TCP                     23m   app=traefik,release=traefik
kube-system   service/traefik              LoadBalancer   10.43.81.189    172.26.0.2    80:31458/TCP,443:30815/TCP   23m   app=traefik,release=traefik

NAMESPACE     NAME                           DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE   CONTAINERS               IMAGES                                                SELECTOR
kube-system   daemonset.apps/svclb-traefik   1         1         1       1            1           <none>          23m   lb-port-80,lb-port-443   rancher/klipper-lb:v0.1.2,rancher/klipper-lb:v0.1.2   app=svclb-traefik
----

== What is klipper ?
== What is Traefik ?