= K3D

NOTE: created using *aur/rancher-k3d-bin 3.1.1-1* on Manjaro Linux using kernel *5.4.67* 

== Initialize your environment

=== Install the tool

[source,bash]
----
$ yay -S aur/rancher-k3d-bin 
----

=== Configure the autocompletion

[source,bash]
----
$ k3d completion zsh > .zsh/completion/_k3d
----

https://rancher.com/docs/k3s/latest/en/installation/
https://rancher.com/docs/k3s/latest/en/networking/

== Create kubernetes clusters

=== Create a single node cluster

Let's create a cluster with only 1 server

[source,bash]
----
$ k3d cluster create demo
----

Using the `kubectl get nodes`, we can see that we have 1 master as requested

[source,bash]
----      
$ kubectl get nodes

NAME                STATUS   ROLES    AGE   VERSION
k3d-demo-server-0   Ready    master   52s   v1.18.9+k3s1
----

Using the `k3d node list`, we have a similar output with 1 master but also an xref:references.adoc#_why_do_we_have_an_extra_loadbalancer_node[extra loadbalancer node].

[source,bash]
----      
$ k3d node list

NAME                ROLE           CLUSTER   STATUS
k3d-demo-server-0   server         demo      running
k3d-demo-serverlb   loadbalancer   demo      running
----

We can now display the cluster-info the same way as with a "normal" kubernetes cluster.

[source,bash]
----           
$ kubectl cluster-info

Kubernetes master is running at https://0.0.0.0:43081
CoreDNS is running at https://0.0.0.0:43081/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
Metrics-server is running at https://0.0.0.0:43081/api/v1/namespaces/kube-system/services/https:metrics-server:/proxy
----

The cluster comes with a bunch of component pre-installed : coredns, klipper, metrics-server, traefik
TODO : Add links to corresponding references pages

[source,bash]
----
$ kubectl get pod,svc,daemonset,deployment --all-namespaces

NAMESPACE     NAME                                         READY   STATUS      RESTARTS   AGE
kube-system   pod/local-path-provisioner-6d59f47c7-46qjg   1/1     Running     0          26m
kube-system   pod/metrics-server-7566d596c8-tz5mg          1/1     Running     0          26m
kube-system   pod/helm-install-traefik-vpk74               0/1     Completed   0          26m
kube-system   pod/svclb-traefik-g4jm4                      2/2     Running     0          25m
kube-system   pod/coredns-7944c66d8d-gbmmh                 1/1     Running     0          26m
kube-system   pod/traefik-758cd5fc85-7tdjc                 1/1     Running     0          25m

NAMESPACE     NAME                         TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
default       service/kubernetes           ClusterIP      10.43.0.1       <none>        443/TCP                      26m
kube-system   service/kube-dns             ClusterIP      10.43.0.10      <none>        53/UDP,53/TCP,9153/TCP       26m
kube-system   service/metrics-server       ClusterIP      10.43.147.126   <none>        443/TCP                      26m
kube-system   service/traefik-prometheus   ClusterIP      10.43.20.11     <none>        9100/TCP                     25m
kube-system   service/traefik              LoadBalancer   10.43.165.93    172.18.0.2    80:32394/TCP,443:32586/TCP   25m

NAMESPACE     NAME                           DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
kube-system   daemonset.apps/svclb-traefik   1         1         1       1            1           <none>          25m

NAMESPACE     NAME                                     READY   UP-TO-DATE   AVAILABLE   AGE
kube-system   deployment.apps/local-path-provisioner   1/1     1            1           26m
kube-system   deployment.apps/metrics-server           1/1     1            1           26m
kube-system   deployment.apps/coredns                  1/1     1            1           26m
kube-system   deployment.apps/traefik                  1/1     1            1           25m
----

Tear the cluster down

[source,bash]
----
$  k3d cluster delete demo
----

=== Create a more complex cluster

Let's create a cluster with with 3 servers and 3 agents

[source,bash]
----
$ k3d cluster create demo --servers 3 --agents 3
----

Using the `k3d node list`, we can see that we have 3 masters and 3 agents as requested

[source,bash]
----           
$ k3d node list

NAME                ROLE           CLUSTER   STATUS
k3d-demo-agent-0    agent          demo      running
k3d-demo-agent-1    agent          demo      running
k3d-demo-agent-2    agent          demo      running
k3d-demo-server-0   server         demo      running
k3d-demo-server-1   server         demo      running
k3d-demo-server-2   server         demo      running
k3d-demo-serverlb   loadbalancer   demo      running
----

Tear the cluster down
[source,bash]
----
$ k3d cluster delete demo
----

=== Create a cluster without pre-installed LoadBalancer

This could be usefull if you want to deploy Traefik with a custom configuration using helm afterwards or your own implementation of LoadBalancer.

Create the cluster
[source,bash]
----
$ k3d cluster create demo --k3s-server-arg "--disable=traefik"
----

The cluster comes without traefik components as requested, note that we also can't see any `svclb` components anymore (klipper), since they were linked to traefik as well.

TODO Link to Klipper 

[source,bash]
----
$ kubectl get pod,svc,daemonset,deployment --all-namespaces

NAMESPACE     NAME                                         READY   STATUS    RESTARTS   AGE
kube-system   pod/local-path-provisioner-6d59f47c7-nc6r8   1/1     Running   0          34s
kube-system   pod/metrics-server-7566d596c8-4f4db          1/1     Running   0          34s
kube-system   pod/coredns-7944c66d8d-w74vf                 1/1     Running   0          34s

NAMESPACE     NAME                     TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)                  AGE
default       service/kubernetes       ClusterIP   10.43.0.1     <none>        443/TCP                  48s
kube-system   service/kube-dns         ClusterIP   10.43.0.10    <none>        53/UDP,53/TCP,9153/TCP   46s
kube-system   service/metrics-server   ClusterIP   10.43.19.57   <none>        443/TCP                  46s

NAMESPACE     NAME                                     READY   UP-TO-DATE   AVAILABLE   AGE
kube-system   deployment.apps/local-path-provisioner   1/1     1            1           46s
kube-system   deployment.apps/metrics-server           1/1     1            1           46s
kube-system   deployment.apps/coredns                  1/1     1            1           46
----

Tear the cluster down
[source,bash]
----
$ k3d cluster delete demo
----

=== Expose the cluster's API on a specific port

[source,bash]
----
$ k3d cluster create demo --api-port 6550 
----

TODO: Test access


Tear the cluster down
[source,bash]
----
$ k3d cluster delete demo
----

=== Expose the loadbalancer's ports on specific ports

[source,bash]
----
$ k3d cluster create demo -p 8081:80@loadbalancer -p8443:443@loadbalancer 
----

TODO: Test access

Tear the cluster down
[source,bash]
----
$ k3d cluster delete demo
----

=== Use all together, to install cluster using ISTIO 


[source,bash]
----
$ k3d cluster create demo --api-port 6550 -p 8081:80@loadbalancer -p8443:443@loadbalancer --servers 1 --agents 3 --k3s-server-arg "--disable=traefik"
----

Tear the cluster down
[source,bash]
----
$ k3d cluster delete demo
----